#//TODO
services:
  tech_challenge_app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tech_challenge_net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/tech_challenge?createDatabaseIfNotExist=true
    depends_on:
      - mysql

    volumes:
      - .m2:/root/.m2

  mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - tech_challenge_net
    environment:
      MYSQL_DATABASE: tech_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

networks:
  tech_challenge_net:
    driver: bridge